/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./../../src/components/Alert.vue')['default']
    Description: typeof import('./../../src/components/description.vue')['default']
    Dropdown: typeof import('./../../src/components/Dropdown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./../../src/components/Footer.vue')['default']
    HelloWorld: typeof import('./../../src/components/HelloWorld.vue')['default']
    Login: typeof import('./../../src/components/Login.vue')['default']
    Nav: typeof import('./../../src/components/Nav.vue')['default']
    Navigation: typeof import('./../../src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
